services:
  php:
    container_name: "codesolluzi.php"
    build: .
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - /home/mauro/.composer:/root/.composer
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    container_name: codesolluzi.com
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

networks:
  default:
    name: codesolluzi.network
    external: true
